global:
  scrape_interval: '15s'

scrape_configs:
  - job_name: 'prometheus'
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: 'admin'
      password: 'password'

alerting:
  alertmanagers:
    - scheme: 'http'
      tls_config:
        insecure_skip_verify: true
